apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment-webhook.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/OWNER/claude-personal-helper2
    newTag: latest
