apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
configMapGenerator:
  - name: telegram-bot-config
    namespace: telegram-bot
    literals:
      - BOT_DEBUG=false
      - BOT_DATABASE_URL=sqlite+aiosqlite:///data/bot.db
